# Generated by Django 6.0.4 on 2026-04-25 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
        ("portfolio", "0006_tecnologia_categoria_tfc_destaque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="portfolio.docente",
            ),
        ),
        migrations.DeleteModel(
            name="Professor",
        ),
    ]
