# Generated by Django 6.0.4 on 2026-04-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_lusofona", models.URLField(blank=True)),
                ("departamento", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("url_site", models.URLField(blank=True)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="licenciatura/")),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "entidade_relacionada",
                    models.CharField(
                        choices=[
                            ("licenciatura", "Licenciatura"),
                            ("uc", "Unidade Curricular"),
                            ("projeto", "Projeto"),
                            ("tecnologia", "Tecnologia"),
                            ("tfc", "TFC"),
                            ("competencia", "Competência"),
                            ("formacao", "Formação"),
                            ("experiencia", "Experiência"),
                            ("geral", "Geral"),
                        ],
                        default="geral",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField(blank=True)),
                ("erros_correcoes", models.TextField(blank=True)),
                ("foto_papel", models.ImageField(blank=True, upload_to="makingof/")),
                ("uso_ia", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Making Of",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("url_site", models.URLField(blank=True)),
                ("nivel_interesse", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=200)),
                ("descricao", models.CharField(max_length=150)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "competencias_adquiridas",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("ano", models.IntegerField()),
                ("link_documento", models.URLField()),
                ("destaque", models.BooleanField(default=False)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField(default=6)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                ("url_programa", models.URLField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(blank=True, to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True, null=True)),
                ("link_github", models.URLField(blank=True, null=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
