# Generated by Django 6.0.4 on 2026-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docente",
            name="departamento",
        ),
        migrations.AddField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, upload_to="docentes/"),
        ),
    ]
