# Generated by Django 6.0.4 on 2026-04-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_docente_departamento_docente_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="destaque",
        ),
    ]
