# Generated by Django 6.0.4 on 2026-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_tfc_destaque"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="apresentacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="course_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="curricular_unit_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
    ]
