# Generated by Django 6.0.4 on 2026-04-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_unidadecurricular_apresentacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="descricao",
        ),
    ]
