# Generated by Django 6.0.4 on 2026-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_unidadecurricular_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linguagem", "Linguagem"),
                    ("framework", "Framework"),
                    ("ferramenta", "Ferramenta"),
                    ("base_dados", "Base de Dados"),
                    ("devops", "DevOps"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tfc",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
    ]
